baseURL: "https://alessandro-zanella.github.io/" # Base URL for your site
languageCode: "en-us" # Language code
title: "Alessandro Zanella" # Title of your site
theme: "hugo-PaperMod"

# Optional Parameters
defaultContentLanguage: "en" # Default content language
paginate: 10 # Number of posts per page
disqusShortname: "your-disqus-shortname" # Disqus shortname for comments

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: youtube
      name: My Youtube
      url: https://www.youtube.com/@alessandrozanella
      weight: 30

params:
  defaultTheme: auto
  assets:
    disableFingerprinting: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content", "tags", "category"]
  profileMode:
    enabled: true
    title: "Howdy!" # optional default will be site title
    subtitle: "Select a project to proceed with:"
    imageUrl: "/img/alessandro-profile-p.jpg"
    imageTitle: "Alessandro Zanella dancing"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Dance Wiki
        url: "/dancewiki"
      - name: Youtube
        url: "https://www.youtube.com/channel/UCQRjOoANHHWaTXgIvHdE2uQ"
      - name: Search
        url: "/search"
  socialIcons: # optional
    - name: "Facebook"
      url: "<link>"
    - name: "Youtube"
      url: "<link2>"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
